name: yourfilms

services:
  yourfilms.api:
    build:
      context: .
      dockerfile: YourFilms/Dockerfile
    container_name: yourfilms.api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - yourfilms.db
      - yourfilms.cache

  yourfilms.web:
    build:
      context: ../YourFilms-web
      dockerfile: Dockerfile
    container_name: yourfilms.web
    ports:
      - "3000:80"
    depends_on:
      - yourfilms.api

  yourfilms.db:
    image: postgres:17-alpine
    container_name: yourfilms.db
    environment:
      POSTGRES_USER: yourfilms
      POSTGRES_PASSWORD: yourfilmspassword
      POSTGRES_DB: yourfilmsdb
    volumes:
      - db-data:/var/lib/postgresql/data

  yourfilms.cache:
    image: redis:latest
    container_name: yourfilms.cache
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
